[control]
server-a ansible_host=10.149.245.110

[app]
server-b ansible_host=10.149.245.115

[monitor]
server-c ansible_host=10.149.245.116

[all:vars]
ansible_user=vagrant
ansible_ssh_pass=vagrant
# 内部ネットワーク(10.149...)での通信なのでポートは標準の 22 です
ansible_port=22